import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProviderWrapper from "./utils/sessionProvider";
import Navbar from "./components/nav";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Get A Quote For Your App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <SessionProviderWrapper> {/* Wrap children inside the Providers component */}
          <Navbar />
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
